name: stagexl_web
description: The website for the dartflash library.
dependencies:
  browser: any
  stagexl:
    git:
      ref: master
      url: https://github.com/bp74/StageXL.git
  stagexl_flump:
    git:
      ref: master
      url: https://github.com/bp74/StageXL_Flump.git
